@startuml DKAvisen
!theme plain


object newspaper {
  {static}nTitle
  fDate
  periodicity
}

object edition {
  {static}eID
  pDate
}

object article {
  {static}title
  text
  topic
  readCount
}

object photo {
  {static}title
  shotDate
}

object journalist {
  {static}cpr
  name
  \tfirstName
  \tlastName
  address
    \tstreetName
    \tcivic
    \tcity
    \tzipCode
    \tcountry  
  telephoneNumbers
  emailAddresses
}

rectangle role{
}


hexagon writes{
}

hexagon publishes{
}

hexagon edits{
}

hexagon contains {
}

hexagon shoots{
}

hexagon includes {
}

newspaper <-right- publishes
publishes -right- edition
edition <-right- contains
edition <-right- edits
edits -right- journalist
contains -right- article
article -right- writes
article -right- writes
writes .left role
writes -right- journalist
photo -down- shoots
shoots -down-> journalist
article -down- includes
includes -down- photo

@enduml
